// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myhircpaqwcwymwekpzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15aGlyY3BhcXdjd3ltd2VrcHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDUzODMsImV4cCI6MjA2NjkyMTM4M30.jaJAqdu8XelOqRQdIr083Tr-yDe2vokqgOSYBSQGjJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});